export const scenes = {
  START: 'START_SCENE',
  SELECT_STICKERS: 'SELECT_STICKERS_SCENE',
  CONFIRM_STICKERS: 'CONFIRM_STICKERS_SCENE',
  DELIVERY: 'DELIVERY_SCENE',
  ORDER_CONFIRMED: 'ORDER_CONFIRMED_SCENE',
  QUESTIONS: 'QUESTIONS_SCENE',
  REQUEST_CONTACT: 'REQUEST_CONTACT_SCENE',
}
